CREATE TABLE BANK_ACCOUNT (
  ID INTEGER IDENTITY PRIMARY KEY,
  ACC_NUMBER  INTEGER,
  BALANCE INTEGER
);

INSERT INTO BANK_ACCOUNT (ID, "NUMBER", BALANCE) VALUES (1010,1010, 100);
INSERT INTO BANK_ACCOUNT (ID, "NUMBER", BALANCE) VALUES (1020,1020, 200);
